In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [26]:
np.random.seed(123)
headers = ["carat",	"cut","color","clarity","depth","table","price","x","y","z"]
data = pd.read_csv('diamonds1.1.csv', na_values='?',    
         header=None,  names = headers) 

data = data.iloc[1:,:]

d_cut = {"Ideal":5,"Premium":4,"Very Good":3,"Good":2,"Fair":1}
d_color = {"D":7,"E":6,"F":5,"G":4,"H":3,"I":2,"J":1}
d_clarity = {"IF":8,"VVS1":7,"VVS2":6,"VS1":5,"VS2":4,"SI1":3,"SI2":2,"I1":4}
 


data["cut"] = data["cut"].map(d_cut)
data["color"] = data["color"].map(d_color)
data["clarity"] = data["clarity"].map(d_clarity)
# data["x"] = data["x"]
# data["y"] = data["y"]
# data["z"] = data["z"]
# data["price"] = data["price"]
# data["carat"] = data["carat"]
# data["table"] = data["table"]
# data["depth"] = data["depth"]
n = data.values.astype(np.double)
data_final = pd.DataFrame(n)

corr_matrix = data_final.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find index of feature columns with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.75)]
#print(corr_matrix)
data_final.drop(data_final.columns[[8,9]], axis = 1)
data_final.drop(data_final.columns[[0, 4, 2]], axis = 1, inplace = True)
data_final


<class 'pandas.core.frame.DataFrame'>


1    3     5        6     7     8     9
0    5.0  8.0  56.0  17590.0  6.55  6.44  4.03
1    4.0  2.0  59.0  17591.0  8.90  8.82  5.29
2    4.0  4.0  60.0  17592.0  8.12  8.06  4.94
3    5.0  5.0  55.0  17595.0  7.72  7.65  4.78
4    3.0  4.0  60.0  17597.0  7.65  7.68  4.66
..   ...  ...   ...      ...   ...   ...   ...
418  5.0  5.0  57.0  18571.0  7.60  7.63  4.61
419  2.0  3.0  59.0  18572.0  7.98  8.03  5.05
420  1.0  3.0  64.0  18574.0  7.43  6.64  4.69
421  4.0  2.0  60.0  18575.0  8.28  8.21  5.02
422  5.0  2.0  55.0  18578.0  8.19  8.14  5.03

[423 rows x 7 columns]

In [20]:
R3 = np.corrcoef(n, None, rowvar=False)
R3

array([[ 1.        , -0.17258795, -0.33035484, -0.47753909,  0.06570808,
         0.18872772,  0.79355595,  0.89082416,  0.88622763,  0.84936391],
       [-0.17258795,  1.        ,  0.00936876,  0.05404531, -0.13207139,
        -0.44383476, -0.08260832, -0.10592798, -0.10936237, -0.12430541],
       [-0.33035484,  0.00936876,  1.        ,  0.02761178, -0.10405707,
         0.03665027, -0.01620278, -0.22210091, -0.22002614, -0.21786718],
       [-0.47753909,  0.05404531,  0.02761178,  1.        , -0.05342556,
        -0.0826684 , -0.22557867, -0.39013419, -0.39171977, -0.38037902],
       [ 0.06570808, -0.13207139, -0.10405707, -0.05342556,  1.        ,
        -0.33328891, -0.05843518, -0.08595377, -0.09630548,  0.07145125],
       [ 0.18872772, -0.44383476,  0.03665027, -0.0826684 , -0.33328891,
         1.        ,  0.16638977,  0.18641348,  0.17980397,  0.14860275],
       [ 0.79355595, -0.08260832, -0.01620278, -0.22557867, -0.05843518,
         0.16638977,  1.        ,  0.84853283

In [23]:
X = data.iloc[:,:-1].values 
Y = data.iloc[:,1].values
X_train, X_test, Y_train, Y_test = train_test_split(  
X, Y, test_size = 1/3, random_state = 0 ) 
weights  = np.zeros(n) 



[[4.1]
 [3.7]
 [1.3]
 [3.2]
 [3.9]
 [2. ]
 [1.1]
 [2.9]
 [4. ]]****
[[3.2]
 [3. ]
 [2.2]
 [4. ]
 [1.5]]****

In [46]:
 
import numpy as np 
import math
import pandas as pd 
  
from sklearn.model_selection import train_test_split 
  
import matplotlib.pyplot as plt 
  
# Linear Regression 
  
class LinearRegression() : 
      
    def __init__( self, learning_rate, iterations ) : 
          
        self.learning_rate = learning_rate 
          
        self.iterations = iterations 
          
    # Function for model training 
              
    def fit( self, X, Y ) : 
          
        # no_of_training_examples, no_of_features 
        self.m, self.n = X.shape 
        
        # weight initialization 
        self.W = np.zeros( self.n ) 
         
        self.b = 0
          
        self.X = X 
          
        self.Y = Y 
        
        # gradient descent learning 
                  
        for i in range( self.iterations ) : 
            self.update_weights() 
        return self
      
    # Helper function to update weights in gradient descent 
      
    def update_weights( self ) : 

        Y_pred = self.predict( self.X ) 
        # calculate gradients   
      
        dW = - ( 2 * ( self.X.T ).dot( self.Y - Y_pred )  ) / self.m 
        db = - 2 * np.sum( self.Y - Y_pred ) / self.m  
          
        # update weights 
        self.W = self.W - self.learning_rate * dW 
        self.b = self.b - self.learning_rate * db 
          
        return self
      
    # Hypothetical function  h( x )  
      
    def predict( self, X ) :
        Wa = 0
        for l in X:
            Wa =Wa + l.dot(self.W)
            if not math.isnan(Wa):
                print(Wa)
        a = (Wa/len(X))+self.b         
        return a 
    
    
    def cost_function(X, Y, B):
        m = len(Y)
        J = np.sum((X.dot(B) — Y) ** 2)/(2 * m)
        return J
     
  
# driver code 
  
def main() : 
      
    # Importing dataset 
      
    df = pd.read_csv( "salaries.csv" ) 
  
    X = df.iloc[:,:-1].values 
  
    Y = df.iloc[:,1].values 
    
    X_train, X_test, Y_train, Y_test = train_test_split(  
      X, Y, test_size = 1/3, random_state = 0 ) 
      
    # Model training 
      
    model = LinearRegression( iterations = 1000, learning_rate = 0.1 ) 
  
    model.fit( X_train, Y_train ) 
      
    # Prediction on test set 
  
    Y_pred = model.predict( X_test ) 
      
    print( "Predicted values ", Y_pred)  
      
    print( "Real values      ", Y_test) 
      
    print( "Trained W        ", round( model.W[0], 2 ) ) 
      
    print( "Trained b        ", round( model.b, 2 ) ) 
      
    # Visualization on test set  
      
    
if __name__ == "__main__" :  
      
    main()

dimensions of weight are  2
values of W are  [0. 0.]
length of X is  8
length of y is  8
X is  [[3.7000e+00 5.7189e+04]
 [1.5000e+00 3.7731e+04]
 [3.2000e+00 6.4445e+04]
 [3.9000e+00 6.3218e+04]
 [2.2000e+00 3.9891e+04]
 [1.3000e+00 4.6205e+04]
 [3.0000e+00 6.0150e+04]
 [4.1000e+00 5.7081e+04]]
Y is  [57189 37731 64445 63218 39891 46205 60150 57081]
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
33521819430178.84
55638166405880.25
93413152004495.31
130468921127724.1
153851370518174.88
180934824743146.2
216192259513634.6
249650773837031.62
-1.900261099831195e+22
-3.1539768749203875e+22
-5.295338438850012e+22
-7.3959295698316586e+22
-8.721417259675042e+22
-1.0256704883957604e+23
-1.2255353313966052e+23
-1.4152025818836693e+23
1.0772065226062338e+31
1.7879040212501717e+31
3.001783863408802e+31
4.19255205196102e+31
4.943935104142848e+31
5.814248053821562e+31
6.947227687721904e+31
8.022399933091791e+31
-6.10639186608879e+39
-1.0135143395061268e+40
-1.701629927279649e+40
-2.3766441449229e+40
-2.80258283558

In [ ]:
import pandas as pd
import numpy
from numpy import asarray
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder

headers = ["carat",	"cut","color","clarity","depth","table","price","x","y","z"]
data = pd.read_csv('diamonds1.1.csv', na_values='?',    
         header=None,  names = headers) 
#data = data.reset_index(drop=True)
#print(type(data))

data = data.iloc[1:,:]


d_cut = {"Ideal":5,"Premium":4,"Very Good":3,"Good":2,"Fair":1}
d_color = {"D":7,"E":6,"F":5,"G":4,"H":3,"I":2,"J":1}
d_clarity = {"IF":8,"VVS1":7,"VVS2":6,"VS1":5,"VS2":4,"SI1":3,"SI2":2,"I1":4}
 


data["cut"] = data["cut"].map(d_cut)
data["color"] = data["color"].map(d_color)
data["clarity"] = data["clarity"].map(d_clarity)


max_price_global = data["price"].max()

n = data.values.astype(numpy.double)

n = n / n.max(axis=0) #normalise data

X_train , X_test = train_test_split(n, test_size=0.15, random_state=42)

In [6]:
columns = np.full((corr.shape[0],), True, dtype=bool)
for i in range(corr.shape[0]):
    for j in range(i+1, corr.shape[0]):
        if corr.iloc[i,j] >= 0.8:
            if columns[j]:
                columns[j] = False
selected_columns = data.columns[columns]
data = data[selected_columns]

In [7]:
print(data)

     carat  cut  color  clarity  depth  table  price     x
0     1.03    5      7        8   62.0   56.0  17590  6.55
1     2.53    4      3        2   59.6   59.0  17591  8.90
2     2.01    4      2        4   61.1   60.0  17592  8.12
3     1.71    5      4        5   62.2   55.0  17595  7.72
4     1.70    3      5        4   60.8   60.0  17597  7.65
..     ...  ...    ...      ...    ...    ...    ...   ...
418   1.60    5      5        5   60.5   57.0  18571  7.60
419   2.01    2      4        3   63.1   59.0  18572  7.98
420   2.01    1      4        3   70.6   64.0  18574  7.43
421   2.11    4      7        2   60.9   60.0  18575  8.28
422   2.03    5      5        2   61.6   55.0  18578  8.19

[423 rows x 8 columns]


In [9]:
iterations = 1000
learning_rate = 0.01
rows , cols = data.shape
print(cols)
print(rows)

8
423


In [56]:
import numpy as np 

def cost_function(X, Y, B):
    m = len(Y)
    J = X.dot(W)
    return J

X = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])

w = np.array([6,7,8,9,3])
loss = X.dot(w)
print(loss)
m  = loss.T.shape
print (m)
# g = X.dot(loss)
# print(g)

[95 95]
(2,)


In [61]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
%matplotlib inline
data = pd.read_csv("diamonds1.1.csv")
print(data.head(5))

   carat        cut color clarity  depth  table  price     x     y     z
0   1.03      Ideal     D      IF   62.0   56.0  17590  6.55  6.44  4.03
1   2.53    Premium     H     SI2   59.6   59.0  17591  8.90  8.82  5.29
2   2.01    Premium     I     VS2   61.1   60.0  17592  8.12  8.06  4.94
3   1.71      Ideal     G     VS1   62.2   55.0  17595  7.72  7.65  4.78
4   1.70  Very Good     F     VS2   60.8   60.0  17597  7.65  7.68  4.66


In [62]:

X = data[:,:4]
y = data[:,6]

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

def cost_function(X, Y, B):
 m = len(Y)
 J = np.sum((X.dot(B) — Y) ** 2)/(2 * m)
 return J


def batch_gradient_descent(X, Y, B, alpha, iterations):
 cost_history = [0] * iterations
 m = len(Y)
 
 for iteration in range(iterations):
 #print(iteration)
 # Hypothesis Values
    h = X.dot(B)
    # Difference b/w Hypothesis and Actual Y
    loss = h — Y
    # Gradient Calculation
    gradient = X.T.dot(loss) / m
    # Changing Values of B using Gradient
    B = B — alpha * gradient
    # New Cost Value
    cost = cost_function(X, Y, B)
    cost_history[iteration] = cost
    
    return B, cost_history

SyntaxError: invalid character in identifier (<ipython-input-62-e1293e5d57c2>, line 10)