In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [58]:
np.random.seed(123)
headers = ["carat",	"cut","color","clarity","depth","table","price","x","y","z"]
data = pd.read_csv('diamonds1.1.csv', na_values='?',    
         header=None,  names = headers) 
data = data.iloc[1:,:]


d_cut = {"Ideal":5,"Premium":4,"Very Good":3,"Good":2,"Fair":1}
d_color = {"D":7,"E":6,"F":5,"G":4,"H":3,"I":2,"J":1}
d_clarity = {"IF":8,"VVS1":7,"VVS2":6,"VS1":5,"VS2":4,"SI1":3,"SI2":2,"I1":4}
 
#label_encoder = LabelEncoder()
#data[:,3] =label_encoder.fit(data[:,3].values)
#print(label_encoder.classes_)
# data[:,1] =label_encoder.fit_transform(data[:,1])
# data[:,2] =label_encoder.fit_transform(data[:,2])
# data[:,3] =label_encoder.fit_transform(data[:,3])


data["cut"] = data["cut"].map(d_cut)
data["color"] = data["color"].map(d_color)
data["clarity"] = data["clarity"].map(d_clarity)




    carat  cut  color  clarity depth table  price     x     y     z
1    1.03    5      7        8    62    56  17590  6.55  6.44  4.03
2    2.53    4      3        2  59.6    59  17591   8.9  8.82  5.29
3    2.01    4      2        4  61.1    60  17592  8.12  8.06  4.94
4    1.71    5      4        5  62.2    55  17595  7.72  7.65  4.78
5     1.7    3      5        4  60.8    60  17597  7.65  7.68  4.66
..    ...  ...    ...      ...   ...   ...    ...   ...   ...   ...
419   1.6    5      5        5  60.5    57  18571   7.6  7.63  4.61
420  2.01    2      4        3  63.1    59  18572  7.98  8.03  5.05
421  2.01    1      4        3  70.6    64  18574  7.43  6.64  4.69
422  2.11    4      7        2  60.9    60  18575  8.28  8.21  5.02
423  2.03    5      5        2  61.6    55  18578  8.19  8.14  5.03

[423 rows x 10 columns]


In [46]:
X = data[['carat', 'cut','color', 'clarity','x','y','z']].values 
Y = data[['price']].values
X_f = pd.DataFrame(X)
Y_f = pd.DataFrame(Y)
X_train, X_test, Y_train, Y_test = train_test_split(  
X, Y, test_size = 1/3, random_state = 0 ) 


print(type(corr_matrix))
corr_matrix.describe()
# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find index of feature columns with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.7)]
X_f.drop(X_f[to_drop], axis=1)

<class 'pandas.core.frame.DataFrame'>


ValueError: Cannot describe a DataFrame without columns

In [34]:
# def correlation(dataset, threshold):
#     col_corr = set() # Set of all the names of deleted columns
#     corr_matrix = dataset.corr()
#     for i in range(len(corr_matrix.columns)):
#         for j in range(i):
#             if (corr_matrix.iloc[i, j] >= threshold) and (corr_matrix.columns[j] not in col_corr):
#                 colname = corr_matrix.columns[i] # getting the name of column
#                 col_corr.add(colname)
#                 if colname in dataset.columns:
#                     del dataset[colname] # deleting the column from the dataset

#     print(dataset)

# Select upper triangle of correlation matrix
# upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# # Find index of feature columns with correlation greater than 0.95
# to_drop = [column for column in upper.columns if any(upper[column] > 0.1)]

# X_f.drop(X_f[to_drop], axis=1)

# print(X_f)

Empty DataFrame
Columns: []
Index: []


In [46]:
 
import numpy as np 
import math
import pandas as pd 
  
from sklearn.model_selection import train_test_split 
  
import matplotlib.pyplot as plt 
  
# Linear Regression 
  
class LinearRegression() : 
      
    def __init__( self, learning_rate, iterations ) : 
          
        self.learning_rate = learning_rate 
          
        self.iterations = iterations 
          
    # Function for model training 
              
    def fit( self, X, Y ) : 
          
        # no_of_training_examples, no_of_features 
        self.m, self.n = X.shape 
        
        # weight initialization 
        self.W = np.zeros( self.n ) 
         
        self.b = 0
          
        self.X = X 
          
        self.Y = Y 
        
        # gradient descent learning 
                  
        for i in range( self.iterations ) : 
            self.update_weights() 
        return self
      
    # Helper function to update weights in gradient descent 
      
    def update_weights( self ) : 

        Y_pred = self.predict( self.X ) 
        # calculate gradients   
      
        dW = - ( 2 * ( self.X.T ).dot( self.Y - Y_pred )  ) / self.m 
        db = - 2 * np.sum( self.Y - Y_pred ) / self.m  
          
        # update weights 
        self.W = self.W - self.learning_rate * dW 
        self.b = self.b - self.learning_rate * db 
          
        return self
      
    # Hypothetical function  h( x )  
      
    def predict( self, X ) :
        Wa = 0
        for l in X:
            Wa =Wa + l.dot(self.W)
            if not math.isnan(Wa):
                print(Wa)
        a = (Wa/len(X))+self.b         
        return a 
    
    
    def cost_function(X, Y, B):
        m = len(Y)
        J = np.sum((X.dot(B) — Y) ** 2)/(2 * m)
        return J
     
  
# driver code 
  
def main() : 
      
    # Importing dataset 
      
    df = pd.read_csv( "salaries.csv" ) 
  
    X = df.iloc[:,:-1].values 
  
    Y = df.iloc[:,1].values 
    
    X_train, X_test, Y_train, Y_test = train_test_split(  
      X, Y, test_size = 1/3, random_state = 0 ) 
      
    # Model training 
      
    model = LinearRegression( iterations = 1000, learning_rate = 0.1 ) 
  
    model.fit( X_train, Y_train ) 
      
    # Prediction on test set 
  
    Y_pred = model.predict( X_test ) 
      
    print( "Predicted values ", Y_pred)  
      
    print( "Real values      ", Y_test) 
      
    print( "Trained W        ", round( model.W[0], 2 ) ) 
      
    print( "Trained b        ", round( model.b, 2 ) ) 
      
    # Visualization on test set  
      
    
if __name__ == "__main__" :  
      
    main()

dimensions of weight are  2
values of W are  [0. 0.]
length of X is  8
length of y is  8
X is  [[3.7000e+00 5.7189e+04]
 [1.5000e+00 3.7731e+04]
 [3.2000e+00 6.4445e+04]
 [3.9000e+00 6.3218e+04]
 [2.2000e+00 3.9891e+04]
 [1.3000e+00 4.6205e+04]
 [3.0000e+00 6.0150e+04]
 [4.1000e+00 5.7081e+04]]
Y is  [57189 37731 64445 63218 39891 46205 60150 57081]
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
33521819430178.84
55638166405880.25
93413152004495.31
130468921127724.1
153851370518174.88
180934824743146.2
216192259513634.6
249650773837031.62
-1.900261099831195e+22
-3.1539768749203875e+22
-5.295338438850012e+22
-7.3959295698316586e+22
-8.721417259675042e+22
-1.0256704883957604e+23
-1.2255353313966052e+23
-1.4152025818836693e+23
1.0772065226062338e+31
1.7879040212501717e+31
3.001783863408802e+31
4.19255205196102e+31
4.943935104142848e+31
5.814248053821562e+31
6.947227687721904e+31
8.022399933091791e+31
-6.10639186608879e+39
-1.0135143395061268e+40
-1.701629927279649e+40
-2.3766441449229e+40
-2.80258283558

In [ ]:
import pandas as pd
import numpy
from numpy import asarray
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder

headers = ["carat",	"cut","color","clarity","depth","table","price","x","y","z"]
data = pd.read_csv('diamonds1.1.csv', na_values='?',    
         header=None,  names = headers) 
#data = data.reset_index(drop=True)
#print(type(data))

data = data.iloc[1:,:]


d_cut = {"Ideal":5,"Premium":4,"Very Good":3,"Good":2,"Fair":1}
d_color = {"D":7,"E":6,"F":5,"G":4,"H":3,"I":2,"J":1}
d_clarity = {"IF":8,"VVS1":7,"VVS2":6,"VS1":5,"VS2":4,"SI1":3,"SI2":2,"I1":4}
 


data["cut"] = data["cut"].map(d_cut)
data["color"] = data["color"].map(d_color)
data["clarity"] = data["clarity"].map(d_clarity)


max_price_global = data["price"].max()

n = data.values.astype(numpy.double)

n = n / n.max(axis=0) #normalise data

X_train , X_test = train_test_split(n, test_size=0.15, random_state=42)

In [6]:
columns = np.full((corr.shape[0],), True, dtype=bool)
for i in range(corr.shape[0]):
    for j in range(i+1, corr.shape[0]):
        if corr.iloc[i,j] >= 0.8:
            if columns[j]:
                columns[j] = False
selected_columns = data.columns[columns]
data = data[selected_columns]

In [7]:
print(data)

     carat  cut  color  clarity  depth  table  price     x
0     1.03    5      7        8   62.0   56.0  17590  6.55
1     2.53    4      3        2   59.6   59.0  17591  8.90
2     2.01    4      2        4   61.1   60.0  17592  8.12
3     1.71    5      4        5   62.2   55.0  17595  7.72
4     1.70    3      5        4   60.8   60.0  17597  7.65
..     ...  ...    ...      ...    ...    ...    ...   ...
418   1.60    5      5        5   60.5   57.0  18571  7.60
419   2.01    2      4        3   63.1   59.0  18572  7.98
420   2.01    1      4        3   70.6   64.0  18574  7.43
421   2.11    4      7        2   60.9   60.0  18575  8.28
422   2.03    5      5        2   61.6   55.0  18578  8.19

[423 rows x 8 columns]


In [9]:
iterations = 1000
learning_rate = 0.01
rows , cols = data.shape
print(cols)
print(rows)

8
423


In [87]:
import numpy as np 

def cost_function(X, Y, B):
    m = len(Y)
    J = X.dot(W)
    return J

X = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5],[1, 1, 1, 1, 1]])

w = np.array([6,7,8,9,3])
loss = X.dot(w)
print("loss is ",loss)
print("weight is ",w)
m  = loss.T.shape
print (m)
# g = X.dot(loss)
# print(g)

loss is  [95 95 33]
weight is  [6 7 8 9 3]
(3,)


In [79]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
%matplotlib inline
headers = ["carat",	"cut","color","clarity","depth","table","price","x","y","z"]
data = pd.read_csv('diamonds1.1.csv', na_values='?',    
         header=None,  names = headers) 
#data = data.reset_index(drop=True)
#print(type(data))

data = data.iloc[1:,:]

#print(type(data))

d_cut = {"Ideal":5,"Premium":4,"Very Good":3,"Good":2,"Fair":1}
d_color = {"D":7,"E":6,"F":5,"G":4,"H":3,"I":2,"J":1}
d_clarity = {"IF":8,"VVS1":7,"VVS2":6,"VS1":5,"VS2":4,"SI1":3,"SI2":2,"I1":4}
 



data["cut"] = data["cut"].map(d_cut)
data["color"] = data["color"].map(d_color)
data["clarity"] = data["clarity"].map(d_clarity)

X = data[['carat','cut','color','clarity','depth','table','x']]
Y = data[['price']]

sc = StandardScaler()
X = sc.fit_transform(X)
print(X)


[[-1.63031974  1.07924945  1.92493008 ...  0.26539485 -0.8853912
  -1.1868065 ]
 [ 1.06177623  0.13406825 -0.49302218 ... -1.27684244  0.50756867
   0.93809444]
 [ 0.12851629  0.13406825 -1.09751025 ... -0.31294413  0.97188862
   0.23280817]
 ...
 [ 0.12851629 -2.70147532  0.11146588 ...  5.79174516  2.82916845
  -0.39109891]
 [ 0.30798936  0.13406825  1.92493008 ... -0.44146391  0.97188862
   0.37748227]
 [ 0.1644109   1.07924945  0.71595395 ...  0.0083553  -1.34971115
   0.29610309]]


In [90]:




import numpy
#print(type(data))



# print(X)
# X_final = X.values.astype(np.double)
# Y_final = Y.values.astype(np.double)
def cost_function(X, Y, B):
    m = len(Y)
    J = np.sum((X.dot(B) - Y) ** 2)/(2 * m)
    return J


def batch_gradient_descent(X, Y, B, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)
    
    for iteration in range(iterations):
    #print(iteration)
    # Hypothesis Values
        h = X.dot(B)
        # Difference b/w Hypothesis and Actual Y
        loss = h - Y
        # Gradient Calculation
        gradient = X.T.dot(loss) / m
        gl,gw = gradient.shape
        print("gradient length ",gl)
        print("gradient width ",gw)
        # Changing Values of B using Gradient
        temp = alpha * gradient
        print(temp)
        B = B - temp
        print(" updated B is ",B)
        # New Cost Value
        #cost = cost_function(X, Y, B)
        #cost_history[iteration] = cost
        
    return B, cost_history

m = 1
f = 7
X_train = X[:m]

print("X_train is ",X_train)

X_train = np.c_[np.ones(len(X_train),dtype='int32'),X_train]
y_train = Y_final[:m]
X_test = X_final[m:]
X_test = np.c_[np.ones(len(X_test),dtype='int32'),X_test]
y_test = Y_final[m:]

# Initial Coefficients
B = np.zeros(X_train.shape[1])
alpha = 0.005
iter_ = 2
newB, cost_history = batch_gradient_descent(X_train, y_train, B, alpha, iter_)


X_train is  [[1 2 3 4 5]]
gradient length  6
gradient width  1
[[ -87.95]
 [ -87.95]
 [-175.9 ]
 [-263.85]
 [-351.8 ]
 [-439.75]]
gradient length  6
gradient width  6
[[ -63.324  -63.324  -63.324  -63.324  -63.324  -63.324]
 [ -63.324  -63.324  -63.324  -63.324  -63.324  -63.324]
 [-126.648 -126.648 -126.648 -126.648 -126.648 -126.648]
 [-189.972 -189.972 -189.972 -189.972 -189.972 -189.972]
 [-253.296 -253.296 -253.296 -253.296 -253.296 -253.296]
 [-316.62  -316.62  -316.62  -316.62  -316.62  -316.62 ]]


In [83]:
print(newB)
weights=[]
for i in range(0,len(newB)):
    weights.append(newB[i][0])



[[  908.50669075   908.50669075   908.50669075   908.50669075
    908.50669075   908.50669075   908.50669075   908.50669075]
 [-1481.15639305 -1481.15639305 -1481.15639305 -1481.15639305
  -1481.15639305 -1481.15639305 -1481.15639305 -1481.15639305]
 [  980.50534218   980.50534218   980.50534218   980.50534218
    980.50534218   980.50534218   980.50534218   980.50534218]
 [ 1748.81186094  1748.81186094  1748.81186094  1748.81186094
   1748.81186094  1748.81186094  1748.81186094  1748.81186094]
 [ 2659.69164484  2659.69164484  2659.69164484  2659.69164484
   2659.69164484  2659.69164484  2659.69164484  2659.69164484]
 [  241.113        241.113        241.113        241.113
    241.113        241.113        241.113        241.113     ]
 [ -804.38382533  -804.38382533  -804.38382533  -804.38382533
   -804.38382533  -804.38382533  -804.38382533  -804.38382533]
 [-1078.22164166 -1078.22164166 -1078.22164166 -1078.22164166
  -1078.22164166 -1078.22164166 -1078.22164166 -1078.22164166]]


In [73]:
m = 70
f = 7
X_train = X[:m]
print(X_train)
X_train = np.c_[np.ones(len(X_train),dtype='int32'),X_train]
y_train = Y_final[:m]
X_test = X_final[m:]
X_test = np.c_[np.ones(len(X_test),dtype='int32'),X_test]
y_test = Y_final[m:]

# Initial Coefficients
B = np.zeros(X_train.shape[1])
alpha = 0.005
iter_ = 2000
newB, cost_history = batch_gradient_descent(X_train, y_train, B, alpha, iter_)

[[-1.63031974e+00  1.07924945e+00  1.92493008e+00  2.92754217e+00
   2.65394853e-01 -8.85391196e-01 -1.18680650e+00]
 [ 1.06177623e+00  1.34068254e-01 -4.93022182e-01 -1.00372874e+00
  -1.27684244e+00  5.07568670e-01  9.38094435e-01]
 [ 1.28516291e-01  1.34068254e-01 -1.09751025e+00  3.06694894e-01
  -3.12944132e-01  9.71888625e-01  2.32808169e-01]
 [-4.09902902e-01  1.07924945e+00  1.11465885e-01  9.61906712e-01
   3.93914628e-01 -1.34971115e+00 -1.28877096e-01]
 [-4.27850209e-01 -8.11112937e-01  7.15953951e-01  3.06694894e-01
  -5.05723793e-01  9.71888625e-01 -1.92172017e-01]
 [-4.27850209e-01 -1.75629413e+00  7.15953951e-01  3.06694894e-01
   3.93914628e-01 -8.85391196e-01 -2.91635465e-01]
 [-1.00216402e+00 -8.11112937e-01  7.15953951e-01  2.92754217e+00
  -2.17648086e+00  9.71888625e-01 -4.90562361e-01]
 [ 1.10568985e-01 -1.75629413e+00 -4.93022182e-01 -3.48516924e-01
   1.10077339e+00  5.07568670e-01  8.81340630e-02]
 [-5.35534047e-01  1.07924945e+00  1.11465885e-01  1.61711853e+0

ValueError: operands could not be broadcast together with shapes (8,) (8,70) 

In [100]:
def r2(y_,y):
 sst = np.sum((y-y.mean())**2)
 ssr = np.sum((y_-y)**2) 
 r2 = 1-(ssr/sst)
 return(r2)

In [104]:
print(B)
print(newB)
print(len(newB))

# for x in X_test:
#     print(x.dot(newB))

[0. 0. 0.]
[1.76737899e+04 9.54549977e+01 9.47673413e-01]
3
